name: All Builds (Linux, macOS, Windows, Android, IPA, APK, AAB)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11
  FLUTTER_VERSION: 3.29.2

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m ensurepip --default-pip
        python -m pip install --upgrade pip setuptools wheel

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Install Linux Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

    - name: Run Flutter Doctor
      run: flutter doctor -v

    - name: Build Linux
      run: |
            flutter config --no-analytics
            flutter build Linux --verbose --build-name=$BUILD_VERSION --build-number=$BUILD_NUMBER

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build-artifact
        path: build/linux
        if-no-files-found: warn

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m ensurepip --default-pip
        python -m pip install --upgrade pip setuptools wheel

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Run Flutter Doctor
      run: flutter doctor -v

    - name: Build macOS
      run: |
            flutter config --no-analytics
            flutter build macOS --verbose --build-name=$BUILD_VERSION --build-number=$BUILD_NUMBER

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build-artifact
        path: build/macos
        if-no-files-found: warn

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m ensurepip --default-pip
        python -m pip install --upgrade pip setuptools wheel

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Run Flutter Doctor
      run: flutter doctor -v

    - name: Build Windows
      run: |
            flutter config --no-analytics
            flutter build Windows --verbose --build-name=$BUILD_VERSION --build-number=$BUILD_NUMBER

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-artifact
        path: build/windows
        if-no-files-found: warn

  build-aab:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Run Flutter Doctor
      run: flutter doctor -v

    - name: Build AAB
      run: |
            flutter config --no-analytics
            flutter build aab --verbose --build-name=$BUILD_VERSION --build-number=$BUILD_NUMBER

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aab-build-artifact
        path: build/app/outputs/bundle/release
        if-no-files-found: warn

  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Run Flutter Doctor
      run: flutter doctor -v

    - name: Build APK
      run: |
            flutter config --no-analytics
            flutter build apk --verbose --build-name=$BUILD_VERSION --build-number=$BUILD_NUMBER

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-build-artifact
        path: build/app/outputs/flutter-apk
        if-no-files-found: warn

  build-ipa:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Run Flutter Doctor
      run: flutter doctor -v

    - name: tkinter Build IPA
      run: |
            flutter config --no-analytics
            flutter build aab --verbose --build-name=$BUILD_VERSION --build-number=$BUILD_NUMBER

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ipa-build-artifact
        path: build/ios
        if-no-files-found: warn
